### ISSUE TITLE
Flexible timing

### ISSUE THREAD

**Issue by rndquu** [ubiquibot/user-activity-watcher#2]
Depends on https://github.com/ubiquibot/user-activity-watcher/pull/1

Right now this plugin supports only thresholds in minutes:
```
- plugin: ubiquibot/user-activity-watcher
  type: github
  with:
    unassignUserThreshold: 7
    sendRemindersThreshold: 3.5
```

It would be useful to support custom string thresholds like: `1 minute`, `2 hours`, `3 days` etc... which could be converted to seconds under the hood.

Example:
```
- plugin: ubiquibot/user-activity-watcher
  type: github
  with:
    unassignUserThreshold: "1 week"
    sendRemindersThreshold: "3 days"
```

What should be done:
- take any battled tested "string to seconds" library ([example](https://www.npmjs.com/package/ms)) and add a feature of supporting string thresholds
